### ISSUE TITLE
Create a base modal component

### ISSUE THREAD

**Issue by EduardoJM** [inventare/design-system#101]
## Tasks

- [x] Create the base styles
- [x] Create base JavaScript to operate the base styles
- [x] Customize the styles to handle our design-system
- [ ] #106
- [x] Finish the JavaScript of modal
- [x] uses the `@inventare/icons` styles for close arrow

## References

- https://dribbble.com/shots/22646409-Company-details-modals-Untitled-UI
- https://dribbble.com/shots/23879907-Edit-user-modal-Untitled-UI
- https://dribbble.com/shots/23714713-Connect-Integration-Popup
